model: RustGraph

anomaly_injection:
  type: "structural"
  train_ratio: 0.5
  val_ratio: 0.1
  test_ratio: 0.1

hyperparameters:
  epochs: 250
  
  learning-rate:
    default:
      type: grid_search
      search_space: [0.0001]
    bitcoin-alpha: 0.001

  emb-dim:
    default:
      type: grid_search
      search_space: [128]

  snapshot_size:
    default:
      type: choice
      search_space: [2000]
    bitcoin-alpha:
      type: grid_search
      search_space: [2000]
    bitcoin-otc: 1000
    email-dnc: 2000
    reddit:
      type: choice
      search_space: [40000, 50000, 60000, 70000]