project-includes = ["src"]
project-excludes = [
    "**/*venv/**/*",
    "src/TADDY/codes/**/*",
    "src/SLADE/evaluation/**/*",
    "src/SLADE/modules/**/*",
    "src/SLADE/utils/**/*",
    "src/SLADE/SLADE_TGN.py",
    "src/SLADE/temporal_attention_SLADE.py",
    "src/SLADE/time_encoding.py"
]

site-package-path = ["venv/lib/python3.11/site-packages"]

python-version = "3.11"
python-interpreter = "venv/bin/python3"

