dataset:
  name: mooc
  paths:
    raw: null
    structured: data/mooc
    processed: null

pipeline:
  cache_dir: pipeline_cache/mooc
  steps:
    - name: TimestampNormalizer

    - name: TemporalSplitter
      params:
        train_ratio: 0.7
        val_ratio: 0.1
