# snapshot_size: 10000
# train_ratio: 0.70
# val_ratio: 0.15
# anomaly_ratio: 0.05

dataset:
  name: as-topology
  paths:
    raw: null
    structured: data/as-topology
    processed: null

pipeline:
  cache_dir: pipeline_cache/as-topology
  steps:
    - name: DataLoader
      params:
        dataset_dir: /mnt/disk2/nazim/dgadb/data/as-topology
    - name: StructureNormalizer
      params:
        directionality: canonical
        reindex_nodes: True
        
    - name: TimestampNormalizer

    - name: TemporalSplitter
      params:
        train_ratio: 0.7
        val_ratio: 0.1

