dataset:
  name: bitcoin-otc

pipeline:
  cache_dir: pipeline_cache/bitcoin-otc
  steps:
    - name: DataLoader
      params:
        dataset_dir: data/bitcoin-otc
    - name: StructureNormalizer
      params:
        directionality: canonical
        reindex_nodes: True
        remove_self_loops: True
        remove_duplicates: True
        
    - name: TimestampNormalizer

    - name: TemporalSplitter
      params:
        train_ratio: 0.5
        val_ratio: 0.25

