# snapshot_size: 1000
# train_ratio: 0.70
# anomaly_ratio: 0.01

dataset:
  name: bitcoin-alpha
  paths:
    raw: null
    structured: data/bitcoin-alpha
    processed: null

# anomalies:
#   anom_train_ratio: 0.5
#   anom_val_ratio: 0.1
#   anom_test_ratio: 0.1

pipeline:
  cache_dir: pipeline_cache/bitcoin-alpha
  steps:
    - name: DataLoader
      params:
        dataset_dir: /mnt/disk2/nazim/dgadb/data/bitcoin-alpha
    - name: StructureNormalizer
      params:
        directionality: canonical
        reindex_nodes: True
        remove_self_loops: False
        remove_duplicates: False
        
    - name: TimestampNormalizer

    - name: TemporalSplitter
      params:
        train_ratio: 0.5
        val_ratio: 0.25

