dataset:
  name: digg-homo

pipeline:
  cache_dir: pipeline_cache/digg-homo
  steps:
    - name: DataLoader
      params:
        dataset_dir: data/digg-homo
    - name: StructureNormalizer
      params:
        directionality: canonical
        reindex_nodes: True
        remove_self_loops: True
        remove_duplicates: True
        
    - name: TimestampNormalizer

    - name: TemporalSplitter
      params:
        train_ratio: 0.5
        val_ratio: 0.25

