dataset:
  name: uc-social

pipeline:
  cache_dir: pipeline_cache/uc-social
  steps:
    - name: DataLoader
      params:
        dataset_dir: /mnt/disk2/nazim/dgadb/data/uc-social
    - name: StructureNormalizer
      params:
        directionality: canonical
        reindex_nodes: True
        remove_self_loops: True
        remove_duplicates: True

    - name: TimestampNormalizer

    - name: TemporalSplitter
      params:
        train_ratio: 0.5
        val_ratio: 0.25
