# snapshot_size: 1000
# train_ratio: 0.70
# val_ratio: 0.10
# anomaly_ratio: 0.01

dataset:
  name: wiki
  paths:
    raw: null
    structured: data/wiki
    processed: null

pipeline:
  cache_dir: pipeline_cache/wiki
  steps:
    - name: DataLoader
      params:
        dataset_dir: data/wiki
    - name: StructureNormalizer
      params:
        directionality: canonical
        reindex_nodes: True
        remove_self_loops: False
        remove_duplicates: False
        
    - name: TimestampNormalizer

    - name: TemporalSplitter
      params:
        train_ratio: 0.7
        val_ratio: 0.1

